[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# 添加remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@uniswap/v2-core/=src/uniswap/v2-core/",
    "@uniswap/v2-periphery/=src/uniswap/v2-periphery/",
    "v2-core/=src/uniswap/v2-core/contracts/",
    "v2-periphery/=src/uniswap/v2-periphery/contracts/"
]

# 使用单一版本编译
solc = "0.8.20"
allow_paths = ["./lib", "./src"]

# 启用多版本编译
[profile.default.model_checker]
contracts = { 'lib/v2-core/contracts/' = ["0.5.16"], 'lib/v2-periphery/contracts/' = ["0.6.6"] }
